name: Java CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        java: [8]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
        java-package: jdk
    - uses: r-lib/actions/setup-r@v1
      with:
        r-version: 3.6
    - run: ls /Library/Frameworks/R.framework/Versions/
      if: matrix.os == 'macos-latest'
    - uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - run: |
        python -m pip install --upgrade pip
        pip install py4j==0.10.8.1
    - run: |
        WD=$PWD
        cd ..
        git clone https://github.com/Funz/funz-profile
        cd $WD
      shell: bash
    - run: ant -noinput -buildfile build.xml test
    - uses: codecov/codecov-action@v1
      if: matrix.os == 'ubuntu-latest'
      
#  release:
#    runs-on: ubuntu-latest
#    
#    steps:
#    - uses: actions/checkout@v2
#    - uses: actions/setup-java@v1
#      with:
#        java-version: 1.8
#        java-package: jdk
#    - run: ant clean dist    
#      if: ${{ github.ref == 'refs/heads/master' }}
#    - uses: actions/upload-artifact@v2
#      with:
#        name: Release
#        path: dist
        
        
        
